resolver: lts-11.3

packages:
  - attoparsec/
  - concurrent/
  - discrimination/
  - eigen/
  # - extensible-effects/
  - foldl/
  # - freer-effects/
  - ghc8/
  - json-stream/
  - lens/
  - linear/
  - massiv/
  - matrices/
  - microlens/
  - pipes/
  - rank2types/
  - recursion-schemes
  - repa/
  - stm/
  # - streaming/
  - xml/

extra-deps:
  - random-eff-0.1.0.1
  - eigen-2.1.7
  - freer-effects-0.3.0.1
  - discrimination-0.2.1
  - promises-0.3
  - streaming-attoparsec-1.0.0
